### ISSUE TITLE
Nullpointer when adding a new file in a PR

### ISSUE THREAD

**Issue by jakub-g** [jsenv/jsenv-file-size-impact#49]
After adding a new HTML file (using 6.0.1), I got a nullpointer in this line (`base` is null so `base.sizeMap` throws):

https://github.com/jsenv/jsenv-file-size-impact/blob/31f8da63c44fb118de48bd59507394aedf876406/src/internal/comment/formatComment.js#L367

**Comment by dmail** [comment]
Good catch you nailed it. 

I should update the doc from `This parameter is null` to `It will crash your program`.

![jsenv-file-size-impact:api md at master · jsenv:jsenv-file-size-impact 2020-11-24 12-01-31](https://user-images.githubusercontent.com/443639/100085847-dcb25900-2e4c-11eb-8466-27fde6e9f555.png)

Or maybe update the code to actually send null 🤔 .

I am joking of course, I guess I will just need to 

```diff
- sizeMapOnBase: base.sizeMap
+ sizeMapOnBase: base ? base.sizeMap : null
```

And maybe also 

```diff
- sizeMapAfterMerge: afterMerge.sizeMap,
+ sizeMapAfterMerge: afterMerge ? afterMerge.sizeMap : null,
```

**Comment by dmail** [comment]
[6.0.2](https://github.com/jsenv/jsenv-file-size-impact/releases/tag/v6.0.2) released with the fix.
You can update version to 6.0.2 in `package.json` :)
